version: '3.8'

services:
  ecommerce:
    build:
      context: .
    container_name: ecommerce-service
    environment:
      - SERVICE_NAME=ecommerce
      - SERVER_PORT=8080
    ports:
      - "8080:8080"

  store:
    build:
      context: .
    container_name: store-service
    environment:
      - SERVICE_NAME=store
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  exchange:
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 2  
    environment:
      - SERVICE_NAME=exchange
      - SERVER_PORT=8082

  fidelity:
    build:
      context: .
    container_name: fidelity-service
    environment:
      - SERVICE_NAME=fidelity
      - SERVER_PORT=8083
    ports:
      - "8083:8083"