version: '3.8'
services:
  e-commerce:
    build:
      context: ./e-commerce
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - store
      - exchange
      - fidelity

  store:
    build:
      context: ./store
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  exchange:
    build:
      context: ./exchange
    ports:
      - "8082:8082"
    deploy:
      replicas: 2
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  fidelity:
    build:
      context: ./fidelity
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod